import { defineField, defineType } from 'sanity';

export const project = defineType({
  name: 'project',
  title: 'Réalisation',
  type: 'document',
  groups: [
    { name: 'chantier', title: 'Le chantier', default: true },
    { name: 'medias', title: 'Photos' },
    { name: 'liens', title: 'Liens' },
    { name: 'seo', title: 'Référencement' },
  ],
  fields: [
    defineField({
      name: 'titre',
      title: 'Titre',
      type: 'string',
      group: 'chantier',
      description: 'Exemple : « Appartement haussmannien, rénovation complète ».',
      validation: (Rule) => Rule.required().max(90),
    }),
    defineField({
      name: 'slug',
      title: 'Adresse de la page',
      type: 'slug',
      group: 'chantier',
      options: { source: 'titre', maxLength: 70 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'typeDeBien',
      title: 'Type de bien',
      type: 'string',
      group: 'chantier',
      options: {
        list: [
          { title: 'Appartement', value: 'appartement' },
          { title: 'Maison', value: 'maison' },
          { title: 'Studio', value: 'studio' },
          { title: 'Local commercial', value: 'local-commercial' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'commune',
      title: 'Commune',
      type: 'reference',
      to: [{ type: 'commune' }],
      group: 'chantier',
      description: 'Sert à filtrer le portfolio et à rattacher le chantier à sa page de commune.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'surface',
      title: 'Surface (m²)',
      type: 'number',
      group: 'chantier',
      validation: (Rule) => Rule.positive().max(10000),
    }),
    defineField({
      name: 'duree',
      title: 'Durée du chantier',
      type: 'string',
      group: 'chantier',
      description: 'Écrivez-la en toutes lettres : « 11 semaines », « 4 mois ».',
    }),
    defineField({
      name: 'budgetRange',
      title: 'Fourchette de budget (facultatif)',
      type: 'string',
      group: 'chantier',
      description: 'Exemple : « 60 – 100 k€ ». Laissez vide si le client ne souhaite pas la voir publiée.',
    }),
    defineField({
      name: 'corpsDeMetier',
      title: 'Corps de métier intervenus',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'service' }] }],
      group: 'liens',
      description: 'Les métiers réellement mobilisés sur ce chantier. Sert au filtrage du portfolio.',
    }),
    defineField({
      name: 'description',
      title: 'Récit du chantier',
      type: 'contenu',
      group: 'chantier',
    }),
    defineField({
      name: 'imageAvant',
      title: 'Photo « avant »',
      type: 'imageAvecAlt',
      group: 'medias',
      description: 'Cadrez au même endroit que la photo « après » : elles se superposent.',
    }),
    defineField({
      name: 'imageApres',
      title: 'Photo « après »',
      type: 'imageAvecAlt',
      group: 'medias',
      description: 'Même angle et même cadrage que la photo « avant ».',
    }),
    defineField({
      name: 'galerie',
      title: 'Galerie',
      type: 'array',
      of: [{ type: 'imageAvecAlt' }],
      group: 'medias',
      options: { layout: 'grid' },
    }),
    defineField({
      name: 'citationClient',
      title: 'Citation du client (facultatif)',
      type: 'citationClient',
      group: 'chantier',
    }),
    defineField({
      name: 'servicesLies',
      title: 'Services à mettre en avant en bas de page',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'service' }] }],
      group: 'liens',
      description: 'Souvent les mêmes que les corps de métier, mais vous pouvez n’en garder que deux ou trois.',
    }),
    defineField({
      name: 'featured',
      title: 'Mettre en avant sur l’accueil',
      type: 'boolean',
      group: 'chantier',
      initialValue: false,
    }),
    defineField({
      name: 'ordre',
      title: 'Ordre d’affichage',
      type: 'number',
      group: 'chantier',
      description: 'Plus le nombre est petit, plus la réalisation apparaît tôt.',
      initialValue: 100,
    }),
    defineField({
      name: 'metaTitle',
      title: 'Titre pour Google',
      type: 'string',
      group: 'seo',
      validation: (Rule) => Rule.max(70),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Description pour Google',
      type: 'text',
      rows: 3,
      group: 'seo',
      validation: (Rule) => Rule.max(170),
    }),
  ],
  orderings: [
    { title: 'Ordre d’affichage', name: 'ordre', by: [{ field: 'ordre', direction: 'asc' }] },
  ],
  preview: {
    select: { title: 'titre', commune: 'commune.nom', surface: 'surface', media: 'imageApres' },
    prepare: ({ title, commune, surface, media }) => ({
      title: title as string,
      subtitle: [commune, surface ? surface + ' m²' : null].filter(Boolean).join(' · '),
      media,
    }),
  },
});
