import { defineField, defineType } from 'sanity';

export const service = defineType({
  name: 'service',
  title: 'Service',
  type: 'document',
  groups: [
    { name: 'contenu', title: 'Contenu', default: true },
    { name: 'medias', title: 'Photos' },
    { name: 'seo', title: 'Référencement' },
  ],
  fields: [
    defineField({
      name: 'titre',
      title: 'Titre',
      type: 'string',
      group: 'contenu',
      description: 'Le nom de la prestation, tel qu’il apparaît en titre de page.',
      validation: (Rule) => Rule.required().max(80),
    }),
    defineField({
      name: 'slug',
      title: 'Adresse de la page',
      type: 'slug',
      group: 'contenu',
      options: { source: 'titre', maxLength: 60 },
      description:
        'Partie de l’adresse après /services/. Une fois la page en ligne, ne la modifiez plus : les liens existants cesseraient de fonctionner.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'resume',
      title: 'Résumé',
      type: 'text',
      rows: 3,
      group: 'contenu',
      description: 'Deux ou trois phrases affichées sous le titre et dans les listes de services.',
      validation: (Rule) => Rule.required().min(60).max(300),
    }),
    defineField({
      name: 'heroImage',
      title: 'Photo principale',
      type: 'imageAvecAlt',
      group: 'medias',
      description:
        'Photo en haut de page. Sert aussi d’aperçu lors du partage sur les réseaux sociaux. Format paysage, 2000 px de large au minimum.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contenu',
      title: 'Contenu de la page',
      type: 'contenu',
      group: 'contenu',
    }),
    defineField({
      name: 'prestations',
      title: 'Ce que comprend la prestation',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'contenu',
      description: 'Une ligne par poste. Affiché en liste à puces.',
    }),
    defineField({
      name: 'faq',
      title: 'Questions fréquentes',
      type: 'array',
      of: [{ type: 'questionReponse' }],
      group: 'contenu',
      description: 'Alimente l’accordéon en bas de page et les données structurées lues par Google.',
    }),
    defineField({
      name: 'galerie',
      title: 'Galerie',
      type: 'array',
      of: [{ type: 'imageAvecAlt' }],
      group: 'medias',
      options: { layout: 'grid' },
    }),
    defineField({
      name: 'ordre',
      title: 'Ordre d’affichage',
      type: 'number',
      group: 'contenu',
      description: 'Plus le nombre est petit, plus le service apparaît haut dans les listes.',
      initialValue: 100,
    }),
    defineField({
      name: 'metaTitle',
      title: 'Titre pour Google',
      type: 'string',
      group: 'seo',
      description: 'Laissez vide pour utiliser « Titre | Bellco Rénovation ». Environ 60 caractères.',
      validation: (Rule) => Rule.max(70),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Description pour Google',
      type: 'text',
      rows: 3,
      group: 'seo',
      description: 'Laissez vide pour reprendre le résumé. Entre 120 et 160 caractères.',
      validation: (Rule) => Rule.max(170),
    }),
  ],
  orderings: [
    { title: 'Ordre d’affichage', name: 'ordre', by: [{ field: 'ordre', direction: 'asc' }] },
  ],
  preview: { select: { title: 'titre', subtitle: 'resume', media: 'heroImage' } },
});
